//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModel
{
	/// <summary>
	/// Database       : HealthBot
	/// Data Source    : tcp://localhost:5432
	/// Server Version : 16.0
	/// </summary>
	public partial class HealthBotDB : LinqToDB.Data.DataConnection
	{
		public ITable<Biometry>   Biometries  { get { return this.GetTable<Biometry>(); } }
		public ITable<DiaryEntry> DiaryEntrys { get { return this.GetTable<DiaryEntry>(); } }
		public ITable<ExportData> ExportDatas { get { return this.GetTable<ExportData>(); } }
		public ITable<IntakeItem> IntakeItems { get { return this.GetTable<IntakeItem>(); } }
		public ITable<Obresver>   Obresvers   { get { return this.GetTable<Obresver>(); } }
		public ITable<User>       Users       { get { return this.GetTable<User>(); } }

		partial void InitMappingSchema()
		{
		}

		public HealthBotDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public HealthBotDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public HealthBotDB(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public HealthBotDB(DataOptions<HealthBotDB> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="public", Name="biometry")]
	public partial class Biometry
	{
		[Column("uuid",       DbType="uuid",                         DataType=LinqToDB.DataType.Guid),                                  PrimaryKey,  NotNull] public Guid            Uuid      { get; set; } // uuid
		[Column("author",     DbType="uuid",                         DataType=LinqToDB.DataType.Guid),                                               NotNull] public Guid            Author    { get; set; } // uuid
		[Column("weight",     DbType="integer",                      DataType=LinqToDB.DataType.Int32,          Precision=32, Scale=0),    Nullable         ] public int?            Weight    { get; set; } // integer
		[Column("height",     DbType="integer",                      DataType=LinqToDB.DataType.Int32,          Precision=32, Scale=0),    Nullable         ] public int?            Height    { get; set; } // integer
		[Column("created_at", DbType="timestamp (6) with time zone", DataType=LinqToDB.DataType.DateTimeOffset, Precision=6),                        NotNull] public DateTimeOffset  CreatedAt { get; set; } // timestamp (6) with time zone
		[Column("changed_at", DbType="timestamp (6) with time zone", DataType=LinqToDB.DataType.DateTimeOffset, Precision=6),              Nullable         ] public DateTimeOffset? ChangedAt { get; set; } // timestamp (6) with time zone
		[Column("deleted_at", DbType="timestamp (6) with time zone", DataType=LinqToDB.DataType.DateTimeOffset, Precision=6),              Nullable         ] public DateTimeOffset? DeletedAt { get; set; } // timestamp (6) with time zone

		#region Associations

		/// <summary>
		/// author (public.users)
		/// </summary>
		[Association(ThisKey="Author", OtherKey="Uuid", CanBeNull=false)]
		public User FKAuthor { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="diaryentrys")]
	public partial class DiaryEntry
	{
		[Column("uuid",             DbType="uuid",                         DataType=LinqToDB.DataType.Guid),                                  PrimaryKey,  NotNull] public Guid           Uuid            { get; set; } // uuid
		[Column("author",           DbType="uuid",                         DataType=LinqToDB.DataType.Guid),                                               NotNull] public Guid           Author          { get; set; } // uuid
		[Column("type",             DbType="text",                         DataType=LinqToDB.DataType.Text),                                               NotNull] public string         Type            { get; set; } // text
		[Column("heart_rate",       DbType="integer",                      DataType=LinqToDB.DataType.Int32,          Precision=32, Scale=0),    Nullable         ] public int?           HeartRate       { get; set; } // integer
		[Column("blood_saturation", DbType="integer",                      DataType=LinqToDB.DataType.Int32,          Precision=32, Scale=0),    Nullable         ] public int?           BloodSaturation { get; set; } // integer
		[Column("blood_preassure",  DbType="text",                         DataType=LinqToDB.DataType.Text),                                     Nullable         ] public string         BloodPreassure  { get; set; } // text
		[Column("created_at",       DbType="timestamp (6) with time zone", DataType=LinqToDB.DataType.DateTimeOffset, Precision=6),                        NotNull] public DateTimeOffset CreatedAt       { get; set; } // timestamp (6) with time zone
		[Column("updated_at",       DbType="timestamp (6) with time zone", DataType=LinqToDB.DataType.DateTimeOffset, Precision=6),                        NotNull] public DateTimeOffset UpdatedAt       { get; set; } // timestamp (6) with time zone
		[Column("deleted_at",       DbType="timestamp (6) with time zone", DataType=LinqToDB.DataType.DateTimeOffset, Precision=6),                        NotNull] public DateTimeOffset DeletedAt       { get; set; } // timestamp (6) with time zone

		#region Associations

		/// <summary>
		/// DiaryEntry_BackReference (public.IntakeItems)
		/// </summary>
		[Association(ThisKey="Uuid", OtherKey="DiaryEntry", CanBeNull=true)]
		public IEnumerable<IntakeItem> DiaryEntries { get; set; }

		/// <summary>
		/// Author (public.users)
		/// </summary>
		[Association(ThisKey="Author", OtherKey="Uuid", CanBeNull=false)]
		public User FKAuthor { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="exportdata")]
	public partial class ExportData
	{
		[Column("uuid",          DbType="uuid",                         DataType=LinqToDB.DataType.Guid),                        PrimaryKey, NotNull] public Guid           Uuid         { get; set; } // uuid
		[Column("author",        DbType="uuid",                         DataType=LinqToDB.DataType.Guid),                                    NotNull] public Guid           Author       { get; set; } // uuid
		[Column("exported_data", DbType="text",                         DataType=LinqToDB.DataType.Text),                                    NotNull] public string         ExportedData { get; set; } // text
		[Column("created_at",    DbType="timestamp (6) with time zone", DataType=LinqToDB.DataType.DateTimeOffset, Precision=6),             NotNull] public DateTimeOffset CreatedAt    { get; set; } // timestamp (6) with time zone

		#region Associations

		/// <summary>
		/// author (public.users)
		/// </summary>
		[Association(ThisKey="Author", OtherKey="Uuid", CanBeNull=false)]
		public User FKAuthor { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="IntakeItems")]
	public partial class IntakeItem
	{
		[Column("uuid",          DbType="uuid",                         DataType=LinqToDB.DataType.Guid),                                  PrimaryKey,  NotNull] public Guid           Uuid         { get; set; } // uuid
		[Column("name",          DbType="text",                         DataType=LinqToDB.DataType.Text),                                               NotNull] public string         Name         { get; set; } // text
		[Column("calory_amount", DbType="integer",                      DataType=LinqToDB.DataType.Int32,          Precision=32, Scale=0),    Nullable         ] public int?           CaloryAmount { get; set; } // integer
		[Column("tags",          DbType="text",                         DataType=LinqToDB.DataType.Text),                                     Nullable         ] public string         Tags         { get; set; } // text
		[Column("state",         DbType="text",                         DataType=LinqToDB.DataType.Text),                                               NotNull] public string         State        { get; set; } // text
		[Column("weight",        DbType="integer",                      DataType=LinqToDB.DataType.Int32,          Precision=32, Scale=0),    Nullable         ] public int?           Weight       { get; set; } // integer
		[Column("diary_entry",   DbType="uuid",                         DataType=LinqToDB.DataType.Guid),                                               NotNull] public Guid           DiaryEntry   { get; set; } // uuid
		[Column("created_at",    DbType="timestamp (6) with time zone", DataType=LinqToDB.DataType.DateTimeOffset, Precision=6),                        NotNull] public DateTimeOffset CreatedAt    { get; set; } // timestamp (6) with time zone
		[Column("updated_at",    DbType="timestamp (6) with time zone", DataType=LinqToDB.DataType.DateTimeOffset, Precision=6),                        NotNull] public DateTimeOffset UpdatedAt    { get; set; } // timestamp (6) with time zone
		[Column("deleted_at",    DbType="timestamp (6) with time zone", DataType=LinqToDB.DataType.DateTimeOffset, Precision=6),                        NotNull] public DateTimeOffset DeletedAt    { get; set; } // timestamp (6) with time zone

		#region Associations

		/// <summary>
		/// DiaryEntry (public.diaryentrys)
		/// </summary>
		[Association(ThisKey="DiaryEntry", OtherKey="Uuid", CanBeNull=false)]
		public DiaryEntry FKDiaryEntry { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="obresvers")]
	public partial class Obresver
	{
		[Column("observer", DbType="uuid", DataType=LinqToDB.DataType.Guid), PrimaryKey(1), NotNull] public Guid Observer { get; set; } // uuid
		[Column("observee", DbType="uuid", DataType=LinqToDB.DataType.Guid), PrimaryKey(2), NotNull] public Guid Observee { get; set; } // uuid

		#region Associations

		/// <summary>
		/// fk_observee (public.users)
		/// </summary>
		[Association(ThisKey="Observee", OtherKey="Uuid", CanBeNull=false)]
		public User Fkobservee { get; set; }

		/// <summary>
		/// fk_observer (public.users)
		/// </summary>
		[Association(ThisKey="Observer", OtherKey="Uuid", CanBeNull=false)]
		public User Fkobserver { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="users")]
	public partial class User
	{
		[Column("uuid",               DbType="uuid",                         DataType=LinqToDB.DataType.Guid),                                  PrimaryKey,  NotNull] public Guid            Uuid              { get; set; } // uuid
		[Column("name",               DbType="text",                         DataType=LinqToDB.DataType.Text),                                     Nullable         ] public string          Name              { get; set; } // text
		[Column("alias",              DbType="text",                         DataType=LinqToDB.DataType.Text),                                     Nullable         ] public string          Alias             { get; set; } // text
		[Column("chat_id",            DbType="bigint",                       DataType=LinqToDB.DataType.Int64,          Precision=64, Scale=0),              NotNull] public long            ChatId            { get; set; } // bigint
		[Column("age",                DbType="integer",                      DataType=LinqToDB.DataType.Int32,          Precision=32, Scale=0),    Nullable         ] public int?            Age               { get; set; } // integer
		[Column("sex",                DbType="text",                         DataType=LinqToDB.DataType.Text),                                     Nullable         ] public string          Sex               { get; set; } // text
		[Column("subscription_end",   DbType="timestamp (6) with time zone", DataType=LinqToDB.DataType.DateTimeOffset, Precision=6),              Nullable         ] public DateTimeOffset? SubscriptionEnd   { get; set; } // timestamp (6) with time zone
		[Column("subscription_start", DbType="timestamp (6) with time zone", DataType=LinqToDB.DataType.DateTimeOffset, Precision=6),              Nullable         ] public DateTimeOffset? SubscriptionStart { get; set; } // timestamp (6) with time zone
		[Column("created_at",         DbType="time with time zone",          DataType=LinqToDB.DataType.Time,           Precision=6),                        NotNull] public DateTimeOffset  CreatedAt         { get; set; } // time with time zone
		[Column("updated_at",         DbType="time with time zone",          DataType=LinqToDB.DataType.Time,           Precision=6),              Nullable         ] public DateTimeOffset? UpdatedAt         { get; set; } // time with time zone
		[Column("deleted_at",         DbType="time with time zone",          DataType=LinqToDB.DataType.Time,           Precision=6),              Nullable         ] public DateTimeOffset? DeletedAt         { get; set; } // time with time zone
		[Column("state",              DbType="text",                         DataType=LinqToDB.DataType.Text),                                               NotNull] public string          State             { get; set; } // text
		[Column("last_action",        DbType="text",                         DataType=LinqToDB.DataType.Text),                                               NotNull] public string          LastAction        { get; set; } // text

		#region Associations

		/// <summary>
		/// author_BackReference (public.biometry)
		/// </summary>
		[Association(ThisKey="Uuid", OtherKey="Author", CanBeNull=true)]
		public IEnumerable<Biometry> AuthorBackReferences { get; set; }

		/// <summary>
		/// author_BackReference (public.exportdata)
		/// </summary>
		[Association(ThisKey="Uuid", OtherKey="Author", CanBeNull=true)]
		public IEnumerable<ExportData> Authors { get; set; }

		/// <summary>
		/// Author_BackReference (public.diaryentrys)
		/// </summary>
		[Association(ThisKey="Uuid", OtherKey="Author", CanBeNull=true)]
		public IEnumerable<DiaryEntry> FKAuthors { get; set; }

		/// <summary>
		/// fk_observee_BackReference (public.obresvers)
		/// </summary>
		[Association(ThisKey="Uuid", OtherKey="Observee", CanBeNull=true)]
		public IEnumerable<Obresver> Fkobservees { get; set; }

		/// <summary>
		/// fk_observer_BackReference (public.obresvers)
		/// </summary>
		[Association(ThisKey="Uuid", OtherKey="Observer", CanBeNull=true)]
		public IEnumerable<Obresver> Fkobservers { get; set; }

		#endregion
	}

	public static partial class TableExtensions
	{
		public static Biometry Find(this ITable<Biometry> table, Guid Uuid)
		{
			return table.FirstOrDefault(t =>
				t.Uuid == Uuid);
		}

		public static DiaryEntry Find(this ITable<DiaryEntry> table, Guid Uuid)
		{
			return table.FirstOrDefault(t =>
				t.Uuid == Uuid);
		}

		public static ExportData Find(this ITable<ExportData> table, Guid Uuid)
		{
			return table.FirstOrDefault(t =>
				t.Uuid == Uuid);
		}

		public static IntakeItem Find(this ITable<IntakeItem> table, Guid Uuid)
		{
			return table.FirstOrDefault(t =>
				t.Uuid == Uuid);
		}

		public static Obresver Find(this ITable<Obresver> table, Guid Observer, Guid Observee)
		{
			return table.FirstOrDefault(t =>
				t.Observer == Observer &&
				t.Observee == Observee);
		}

		public static User Find(this ITable<User> table, Guid Uuid)
		{
			return table.FirstOrDefault(t =>
				t.Uuid == Uuid);
		}
	}
}
